In [1]:
%run ../real/input/Format.ipynb
import os
import numpy as np
import pandas as pd
import ROOT as root
from array import array

root.gErrorIgnoreLevel = root.kFatal
root.gStyle.SetOptStat(0)
root.TH1.AddDirectory(False)

%jsroot on

/home/yoren/.local/lib/python3.10/site-packages/nbformat/__init__.py:96: MissingIDFieldWarning: Cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate(nb)

Welcome to JupyROOT 6.30/06

Error in <TUnixSystem::FindDynamicLibrary>: input/logo/PHENIXTools/lib/libLogoPainter.so does not exist in /home/yoren/bnl/ROOT/install/lib:.:/home/yoren/bnl/ROOT/install/lib:/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3:/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2:/lib/x86_64-linux-gnu/tls/haswell/x86_64:/lib/x86_64-linux-gnu/tls/haswell:/lib/x86_64-linux-gnu/tls/x86_64:/lib/x86_64-linux-gnu/tls:/lib/x86_64-linux-gnu/haswell/x86_64:/lib/x86_64-linux-gnu/haswell:/lib/x86_64-linux-gnu/x86_64:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3:/usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2:/usr/lib/x86_64-linux-gnu/tls/haswell/x86_64:/usr/lib/x86_64-linux-gnu/tls/haswell:/usr/lib/x86_64-linux-gnu/tls/x86_64:/usr/lib/x86_64-linux-gnu/tls:/usr/lib/x86_64-linux-gnu/haswell/x86_64:/usr/lib/x86_64-linux-gnu/haswell:/usr/lib/x86_64-linux-gnu/x86_64:/usr/lib/x86_64-linux-gnu:/lib/glibc-hwcaps/x86-64-v3:/lib/glibc-hwcaps/x86-64-v2:/lib/tls/haswell/x86_64:/lib/tls/haswell:/lib/tls/x86_64:/lib/tls:/lib/haswell/x86_64:/lib/haswell:/lib/x86_64:/lib:/usr/lib/glibc-hwcaps/x86-64-v3:/usr/lib/glibc-hwcaps/x86-64-v2:/usr/lib/tls/haswell/x86_64:/usr/lib/tls/haswell:/usr/lib/tls/x86_64:/usr/lib/tls:/usr/lib/haswell/x86_64:/usr/lib/haswell:/usr/lib/x86_64:/usr/lib:/home/yoren/bnl/ROOT
input_line_46:1:10: fatal error: 'input/logo/PHENIXTools/include/LogoPainter.hpp' file not found
#include "input/logo/PHENIXTools/include/LogoPainter.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [2]:
safe_to_pdf = False

In [3]:
root.TH1.AddDirectory(False)

%jsroot on

In [4]:
colors = [
    root.kBlack, root.kBlue, root.kRed,
    root.kGreen + 2, root.kOrange + 7,
    root.kMagenta, root.kCyan + 2
]

In [5]:
pt_cuau_mb_or = np.array([
    1.25, 1.75, 2.25, 2.75, 3.25, 3.75,
    4.25, 4.75, 5.25, 5.75, 6.25, 6.75,
    7.25, 7.75, 8.25, 8.75, 9.25, 9.75,
    11.0, 13.0, 15.0, 17.0, 19.0
])

y_cuau_mb_or = np.array([
    0.5240061, 0.09060204, 0.01829509, 0.004407103,
    0.001253962, 0.0003987261, 0.0001448726,
    0.00005801032, 0.00002631398, 0.00001240795,
    0.000006331709, 0.000003367263, 0.000001912208,
    0.000001099707, 0.0000006714349, 0.0000004230109,
    0.0000002634574, 0.0000001823898,
    0.00000006783677, 0.00000001905459, 0.000000006200235,
    0.000000002223254, 0.0000000008200898
])

# Stat.+Sys.A
y_cuau_mb_stat = np.array([
    0.008666846, 0.001115351, 0.0001898835, 0.00004225537,
    0.00001126056, 0.000003404332, 0.000001207851,
    0.0000004736954, 0.0000002098626, 0.0000001008402,
    0.00000005381894, 0.00000003105426, 0.00000001914488,
    0.00000001233181, 0.000000007510051, 0.000000005056911,
    0.000000003676483, 0.000000002682878,
    0.0000000007071644, 0.0000000003417906,
    0.0000000001860336, 0.0000000001168828,
    0.00000000007705774
])

# Quadrature of Sys.B and Sys.C
y_cuau_mb_syst = np.array([
    0.0368399194, 0.00668324883, 0.00143364961,
    0.000345184731, 0.000105185874, 0.0000359632816,
    0.0000130683223, 0.00000523230529, 0.00000255622840,
    0.00000120536364, 0.000000615102655, 0.000000327095891,
    0.000000185765144, 0.000000106836897, 0.0000000708758824,
    0.0000000448722915, 0.0000000278304443,
    0.0000000193031386,
    0.000000007751355, 0.000000002239646,
    0.0000000007691815, 0.0000000002991841,
    0.0000000001183857
])

In [6]:
fHagedorn = root.TF1("fHagedorn","((1/(1+exp((x-[5])/[6])))*[0]/(1+x/[1])**[2] + (1-(1/(1+exp((x-[5])/[6]))))*[3]/x**[4])",0.0,20.0)
fHagedorn.SetNpx(10000)
fHagedorn.SetParameters(1.922170e+02, 2.106180e+00, 1.284030e+01, 1.630000e+01, 8.060480e+00, 4.033000e+00, 6.395340e-02) #NEED TO UPDATE PARAMETERS

In [7]:
pt_cuau_mb = np.array([0.1*i for i in range(1, 201)])
y_cuau_mb = np.array([fHagedorn.Eval(pt) for pt in pt_cuau_mb])
y_cuau_mb_stat_rel = y_cuau_mb_stat/y_cuau_mb_or
y_cuau_mb_syst_rel = y_cuau_mb_syst/y_cuau_mb_or

y_cuau_mb_stat = np.array([y_cuau_mb[i] * np.interp(pt_cuau_mb[i], pt_cuau_mb_or, y_cuau_mb_stat_rel) for i in range(len(y_cuau_mb))])
y_cuau_mb_syst = np.array([y_cuau_mb[i] * np.interp(pt_cuau_mb[i], pt_cuau_mb_or, y_cuau_mb_syst_rel) for i in range(len(y_cuau_mb))])

In [8]:
df_rgamma_summary = pd.read_csv("output/final_arrays/rgamma_summary.csv")
#df_rgamma_summary

In [9]:
pt_arr = df_rgamma_summary["pt"].values
rgamma_arr = df_rgamma_summary["rgamma_nominal"].values
stat_arr = df_rgamma_summary["stat_nominal"].values
syst_down_arr = df_rgamma_summary["syst_down"].values
syst_up_arr = df_rgamma_summary["syst_up"].values

print("pt =", pt_arr.tolist())
print("rgamma =", rgamma_arr.tolist())
print("stat =", stat_arr.tolist())
print("syst_down =", syst_down_arr.tolist())
print("syst_up =", syst_up_arr.tolist())

pt = [0.9, 1.15, 1.5, 1.85, 2.25, 2.75, 3.5, 4.5, 6.0, 8.5]
rgamma = [0.9872843448181022, 1.1134052451204548, 1.0354381606117895, 1.0135936092745466, 1.0717892075536417, 1.0156690283112986, 1.15457828642616, 2.9630915432016898, nan, nan]
stat = [0.0216906628767701, 0.0196630147131355, 0.0204111952816233, 0.0310705085839516, 0.0364227009144229, 0.0542316130170337, 0.0870707656355535, 1.137719075753857, nan, nan]
syst_down = [0.6741233082311877, 0.6741233082311877, 0.6741233082311877, 0.6741233082311877, 0.6741233082311877, 0.6741233082311877, 0.6741233082311877, 0.8770212374631083, nan, nan]
syst_up = [0.6741233082311877, 0.6741233082311877, 0.6741233082311877, 0.6741233082311877, 0.6741233082311877, 0.6741233082311877, 0.6741233082311877, 4.733398049479709, nan, nan]

In [10]:
pt_ppg243 = np.array([0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.25, 2.75, 3.25, 3.75, 4.5, 6.0, 8.5])

rgamma_ppg243_40_50 = np.array([1.111, 1.138, 1.147, 1.154, 1.132, 1.142, 1.171, 1.223, 1.214, 1.310, 1.303, 1.398, 1.499])

rgamma_ppg243_40_50_stat = np.array([0.017, 0.013, 0.013, 0.014, 0.015, 0.017, 0.015, 0.023, 0.033, 0.054, 0.052, 0.080, 0.185])

rgamma_ppg243_40_50_syst = np.array([0.052, 0.053, 0.054, 0.054, 0.053, 0.053, 0.054, 0.055, 0.054, 0.057, 0.055, 0.057, 0.061])

ppg243_40_50_stat_gr = root.TGraphErrors(len(pt_ppg243), pt_ppg243, rgamma_ppg243_40_50, np.zeros(len(pt_ppg243)), rgamma_ppg243_40_50_stat)
ppg243_40_50_syst_gr = root.TGraphErrors(len(pt_ppg243), pt_ppg243, rgamma_ppg243_40_50, np.array([0.1]*len(pt_ppg243)), rgamma_ppg243_40_50_syst)



pt_wenq = [0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.25, 2.75, 3.25, 3.75, 4.5, 6.0, 8.5]
pt_err = [0.05] * len(pt_wenq)  # Assuming a constant error of 0.1 GeV/c for all points

rgamma_50_60 = [1.117, 1.145, 1.114, 1.144, 1.149, 1.138, 1.164, 1.159, 1.203, 1.182, 1.176, 1.202, 1.816]

stat_50_60 = [0.016, 0.019, 0.012, 0.013, 0.015, 0.017, 0.014, 0.022, 0.033, 0.047, 0.051, 0.072, 0.297]

syst_50_60 = [0.054, 0.055, 0.053, 0.055, 0.055, 0.054, 0.054, 0.053, 0.054, 0.052, 0.053, 0.050, 0.074]

rgamma_30_40 = [1.132, 1.140, 1.145, 1.151, 1.151, 1.195, 1.218, 1.217, 1.250, 1.286, 1.346, 1.436, 1.832]

stat_30_40 = [0.018, 0.014, 0.014, 0.015, 0.016, 0.019, 0.018, 0.023, 0.035, 0.032, 0.052, 0.082, 0.247]

syst_30_40 = [0.052, 0.052, 0.054, 0.053, 0.052, 0.054, 0.055, 0.054, 0.055, 0.055, 0.055, 0.058, 0.074]

ppg243_50_60 = root.TGraphErrors(len(pt_wenq), array('d', pt_wenq), array('d', rgamma_50_60), array('d', [0]*len(pt_wenq)), array('d', stat_50_60))
ppg243_50_60_syst = root.TGraphErrors(len(pt_wenq), array('d', pt_wenq), array('d', rgamma_50_60), array('d', [0.1]*len(pt_wenq)), array('d', syst_50_60))

ppg243_30_40 = root.TGraphErrors(len(pt_wenq), array('d', pt_wenq), array('d', rgamma_30_40), array('d', [0]*len(pt_wenq)), array('d', stat_30_40))
ppg243_30_40_syst = root.TGraphErrors(len(pt_wenq), array('d', pt_wenq), array('d', rgamma_30_40), array('d', [0.1]*len(pt_wenq)), array('d', syst_30_40))

In [11]:
#drawing beatiful rgamma plot with stat and syst error bars as two lots with P and 2 options
draw_ppg243 = True


c = root.TCanvas("c", "c", 800, 600)

gr_rgamma_stat = root.TGraphErrors(len(pt_arr), array('d', pt_arr), array('d', rgamma_arr), array('d', [0]*len(stat_arr)), array('d', stat_arr))
Format_Hist_total(gr_rgamma_stat, title_x="p_{T} [GeV/c]",  title_y="R_{#gamma}", left=0.15, bottom=0.15, right=0.01, top=0.01,  Tsize=0.06,  Lsize=0.06,\
                      Mstyle=20,  Msize=1.5, Mcolor=1,  Lwidth=3,  Lcolor=1,  offset_x=1, offset_y=1, title="",  Malpha=1,  Lalpha=1)

gr_rgamma_stat.Draw("AP")

gr_rgamma_stat.GetYaxis().SetRangeUser(0.91, 1.85)
gr_rgamma_stat.GetYaxis().SetNdivisions(505)
gr_rgamma_stat.GetXaxis().SetLimits(0.0, 7.0)

if draw_ppg243:
    ppg243_40_50_stat_gr.SetMarkerStyle(21)
    ppg243_40_50_stat_gr.SetMarkerSize(1.5)
    ppg243_40_50_stat_gr.SetMarkerColor(root.kGreen + 2)
    ppg243_40_50_stat_gr.SetLineColor(root.kGreen + 2)
    ppg243_40_50_stat_gr.Draw("P SAME")

    ppg243_40_50_syst_gr.SetFillColorAlpha(root.kGreen + 2, 0.9)
    ppg243_40_50_syst_gr.SetFillStyle(3001)
    ppg243_40_50_syst_gr.Draw("2 SAME")


gr_rgamma_syst = root.TGraphAsymmErrors(len(pt_arr))

for i in range(len(pt_arr)):
    gr_rgamma_syst.SetPoint(i, pt_arr[i], rgamma_arr[i])
    gr_rgamma_syst.SetPointError(i, 0.1, 0.1, syst_down_arr[i], syst_up_arr[i])

gr_rgamma_syst.SetFillColor(root.kBlack)
gr_rgamma_syst.SetFillStyle(3001)
gr_rgamma_syst.SetMarkerStyle(20)
gr_rgamma_syst.SetMarkerSize(1.5)
gr_rgamma_syst.SetMarkerColor(root.kBlack)
gr_rgamma_syst.SetLineColor(root.kBlack)
gr_rgamma_syst.Draw("2 SAME")
gr_rgamma_stat.Draw("SAME P")

legend = root.TLegend(0.3, 0.1, 0.9, 0.3)
legend.SetBorderSize(0)
legend.SetFillStyle(0)
legend.SetNColumns(2)
legend.SetTextSize(0.05)
legend.AddEntry(gr_rgamma_stat, "This Analysis")
if draw_ppg243:
    legend.AddEntry(ppg243_40_50_stat_gr, "PPG243 (40-50)", "p")
#legend.Draw()


legend0 = root.TLegend(0.17, 0.88, 0.99, 0.98,"0%-93% Cu+Au, #sqrt{s_{NN}} = 200 GeV, |#eta|<0.35")
legend0.SetBorderSize(0)
legend0.SetFillStyle(0)
legend0.SetTextSize(0.06)
legend0.Draw()
legend1 = root.TLegend(0.17, 0.69, 0.4, 0.88)
legend1.SetBorderSize(0)
legend1.SetFillStyle(0)
#legend1.SetNColumns(2)
legend1.SetTextSize(0.06)
legend1.AddEntry(gr_rgamma_stat, "0%-93% Cu+Au: dN_{ch}/d#eta #approx 102","p")
if draw_ppg243:
    legend1.AddEntry(ppg243_40_50_stat_gr, "40%-50% Au+Au: dN_{ch}/d#eta #approx 107", "p")
legend1.Draw()


leg5 = root.TLegend(0.21, 0.66, 0.8, 0.66,"PRC109 044912")
leg5.SetBorderSize(0)
leg5.SetFillStyle(0)
leg5.SetTextSize(0.040)
leg5.Draw()


c.Draw()
if safe_to_pdf:c.SaveAs("output/res/rgamma_stat_syst0.pdf")

In [12]:
c.Draw()

In [13]:
#drawing beatiful rgamma plot with stat and syst error bars as two lots with P and 2 options
draw_ppg243 = True


c = root.TCanvas("c", "c", 800, 600)

gr_rgamma_stat = root.TGraphErrors(len(pt_arr), array('d', pt_arr), array('d', rgamma_arr), array('d', [0]*len(stat_arr)), array('d', stat_arr))
Format_Hist_total(gr_rgamma_stat, title_x="p_{T} [GeV/c]",  title_y="R_{#gamma}", left=0.15, bottom=0.15, right=0.01, top=0.01,  Tsize=0.06,  Lsize=0.06,\
                      Mstyle=20,  Msize=1.5, Mcolor=1,  Lwidth=3,  Lcolor=1,  offset_x=1, offset_y=1, title="",  Malpha=1,  Lalpha=1)
gr_rgamma_stat.Draw("AP")

gr_rgamma_stat.GetYaxis().SetRangeUser(0.91, 1.85)
gr_rgamma_stat.GetYaxis().SetNdivisions(505)
#gr_rgamma_stat.GetYaxis().SetRangeUser(0.5, 3)
gr_rgamma_stat.GetXaxis().SetLimits(0.0, 7.0)

if draw_ppg243:
    ppg243_30_40.SetMarkerStyle(22)
    ppg243_30_40.SetMarkerSize(1.5)
    ppg243_30_40.SetMarkerColor(root.kMagenta)
    ppg243_30_40.SetLineColor(root.kMagenta)
    ppg243_30_40.Draw("P SAME")

    ppg243_30_40_syst.SetFillColorAlpha(root.kMagenta, 0.7)
    ppg243_30_40_syst.SetFillStyle(3001)
    ppg243_30_40_syst.Draw("2 SAME")

    ppg243_50_60.SetMarkerStyle(23)
    ppg243_50_60.SetMarkerSize(1.5)
    ppg243_50_60.SetMarkerColor(root.kCyan)
    ppg243_50_60.SetLineColor(root.kCyan)
    ppg243_50_60.Draw("P SAME")

    ppg243_50_60_syst.SetFillColorAlpha(root.kCyan, 0.7)
    ppg243_50_60_syst.SetFillStyle(3001)
    ppg243_50_60_syst.Draw("2 SAME")

    ppg243_40_50_stat_gr.SetMarkerStyle(21)
    ppg243_40_50_stat_gr.SetMarkerSize(1.5)
    ppg243_40_50_stat_gr.SetMarkerColor(root.kGreen + 2)
    ppg243_40_50_stat_gr.SetLineColor(root.kGreen + 2)
    ppg243_40_50_stat_gr.Draw("P SAME")

    ppg243_40_50_syst_gr.SetFillColorAlpha(root.kGreen + 2, 0.7)
    ppg243_40_50_syst_gr.SetFillStyle(3001)
    ppg243_40_50_syst_gr.Draw("2 SAME")


gr_rgamma_syst = root.TGraphAsymmErrors(len(pt_arr))

for i in range(len(pt_arr)):
    gr_rgamma_syst.SetPoint(i, pt_arr[i], rgamma_arr[i])
    gr_rgamma_syst.SetPointError(i, 0.1, 0.1, syst_down_arr[i], syst_up_arr[i])

gr_rgamma_syst.SetFillColor(root.kBlack)
gr_rgamma_syst.SetFillStyle(3001)
gr_rgamma_syst.SetMarkerStyle(20)
gr_rgamma_syst.SetMarkerSize(1.5)
gr_rgamma_syst.SetMarkerColor(root.kBlack)
gr_rgamma_syst.SetLineColor(root.kBlack)
gr_rgamma_syst.Draw("2 SAME")
gr_rgamma_stat.Draw("SAME P")

legend = root.TLegend(0.3, 0.1, 0.9, 0.3)
legend.SetBorderSize(0)
legend.SetFillStyle(0)
legend.SetNColumns(2)
legend.SetTextSize(0.05)
legend.AddEntry(gr_rgamma_stat, "This Analysis")
if draw_ppg243:
    legend.AddEntry(ppg243_40_50_stat_gr, "PPG243 (40-50)", "p")
    legend.AddEntry(ppg243_50_60, "PPG243 (50-60)", "p")
    legend.AddEntry(ppg243_30_40, "PPG243 (30-40)", "p")
#legend.Draw()


legend0 = root.TLegend(0.17, 0.90, 0.99, 0.98,"0%-93% Cu+Au, #sqrt{s_{NN}} = 200 GeV, |#eta|<0.35")
legend0.SetBorderSize(0)
legend0.SetFillStyle(0)
legend0.SetTextSize(0.06)
legend0.Draw()
legend1 = root.TLegend(0.17, 0.62, 0.4, 0.9)
legend1.SetBorderSize(0)
legend1.SetFillStyle(0)
#legend1.SetNColumns(2)
legend1.SetTextSize(0.06)
legend1.AddEntry(gr_rgamma_stat, "0%-93% Cu+Au: dN_{ch}/d#eta #approx 102", "p")
if draw_ppg243:
    legend1.AddEntry(ppg243_40_50_stat_gr, "40%-50% Au+Au: dN_{ch}/d#eta #approx 107", "p")
    legend1.AddEntry(ppg243_50_60, "50%-60% Au+Au: dN_{ch}/d#eta #approx 62", "p")
    legend1.AddEntry(ppg243_30_40, "30%-40% Au+Au: dN_{ch}/d#eta #approx 171", "p")
legend1.Draw()


leg5 = root.TLegend(0.21, 0.58, 0.8, 0.60,"PRC109 044912")
leg5.SetBorderSize(0)
leg5.SetFillStyle(0)
leg5.SetTextSize(0.040)
leg5.Draw()


c.Draw()
if safe_to_pdf:
    c.SaveAs("output/res/rgamma_stat_syst1.pdf")

In [14]:
c.Draw()

In [15]:
import numpy as np

# Cu+Au @ 200 GeV, 0-20%
# ratio = gamma_hadron / gamma_pi0


pt_ratio = np.array([
    0.55, 0.60, 0.70, 0.80, 0.90, 1.00,
    1.25, 1.50, 1.75, 2.00, 2.25, 2.50,
    2.75, 3.00, 3.50, 4.00, 4.50, 5.00,
    5.50, 6.00, 6.50, 7.00, 7.50, 8.00,
    8.50, 9.00, 9.50, 9.90
])

ratio_vals = np.array([
    1.09696, 1.11315, 1.13620, 1.14979, 1.15773, 1.16320,
    1.17504, 1.18419, 1.19127, 1.19712, 1.20184, 1.20584,
    1.20926, 1.21221, 1.21708, 1.22092, 1.22365, 1.22579,
    1.22739, 1.22838, 1.22922, 1.22976, 1.22995, 1.23024,
    1.23024, 1.23028, 1.22996, 1.22980
])

def gamma_hadron_over_gamma_pi0(pt):
    return np.interp(pt, pt_ratio, ratio_vals)

In [16]:
import numpy as np

M_PI0 = 0.1349768  # GeV/c^2

def pi0_inv_spectrum(pt):
    return np.interp(pt, pt_cuau_mb, y_cuau_mb, left=0.0, right=0.0)

def pi0_dndpt_spectrum(pt):
    # input pi0 is invariant yield:
    # inv = 1/(2*pi*pT) dN/dpTdy
    return 2.0 * np.pi * pt * pi0_inv_spectrum(pt)

def boost_x(px, py, pz, e, beta):
    gamma = 1.0 / np.sqrt(1.0 - beta * beta)
    px_new = gamma * (px + beta * e)
    e_new = gamma * (e + beta * px)
    return px_new, py, pz, e_new

def run_pi0_decay_mc(n_mc=2_000_000, pt_parent_min=0.0, pt_parent_max=20.0, seed=12345):
    rng = np.random.default_rng(seed)

    # Generate parent pi0 pT uniformly, weight by physical dN/dpT
    pt_pi0 = rng.uniform(pt_parent_min, pt_parent_max, n_mc)
    w_pi0 = pi0_dndpt_spectrum(pt_pi0)

    # Parent pi0 at y=0 and phi=0; pT distribution only, phi symmetry irrelevant
    e_pi0 = np.sqrt(pt_pi0**2 + M_PI0**2)
    beta = pt_pi0 / e_pi0

    # Isotropic two-body decay in pi0 rest frame
    costh = rng.uniform(-1.0, 1.0, n_mc)
    sinth = np.sqrt(1.0 - costh**2)
    phi = rng.uniform(0.0, 2.0*np.pi, n_mc)

    e_star = M_PI0 / 2.0
    p_star = M_PI0 / 2.0

    px1_star = p_star * sinth * np.cos(phi)
    py1_star = p_star * sinth * np.sin(phi)
    pz1_star = p_star * costh

    px2_star = -px1_star
    py2_star = -py1_star
    pz2_star = -pz1_star

    px1, py1, pz1, e1 = boost_x(px1_star, py1_star, pz1_star, e_star, beta)
    px2, py2, pz2, e2 = boost_x(px2_star, py2_star, pz2_star, e_star, beta)

    pt_g1 = np.sqrt(px1**2 + py1**2)
    pt_g2 = np.sqrt(px2**2 + py2**2)

    return pt_pi0, w_pi0, pt_g1, pt_g2

In [17]:
pt_edges = np.array(
    df_rgamma_summary["pt_low"].dropna().tolist()
    + [df_rgamma_summary["pt_high"].dropna().iloc[-1]]
)
pt_edges = np.unique(pt_edges)

pt_centers = 0.5 * (pt_edges[:-1] + pt_edges[1:])
pt_widths = pt_edges[1:] - pt_edges[:-1]

N_PI0_DECAY_MC = 3_000_000
PT_PARENT_MIN = 0.0
PT_PARENT_MAX = 20.0

pt_pi0_mc, w_pi0_mc, pt_g1_mc, pt_g2_mc = run_pi0_decay_mc(
    n_mc=N_PI0_DECAY_MC,
    pt_parent_min=PT_PARENT_MIN,
    pt_parent_max=PT_PARENT_MAX,
    seed=12345
)

# Uniform-MC integration normalization:
# integral f(pT) dpT ≈ (range / N) * sum_i f(pT_i)
mc_norm = (PT_PARENT_MAX - PT_PARENT_MIN) / float(N_PI0_DECAY_MC)

# Parent pi0 dN in pT bins
h_pi0_dN_raw, _ = np.histogram(pt_pi0_mc, bins=pt_edges, weights=w_pi0_mc)
h_pi0_dN = mc_norm * h_pi0_dN_raw

# Decay photons dN in pT bins; each pi0 gives two photons with same parent weight
h_gam_dN_1_raw, _ = np.histogram(pt_g1_mc, bins=pt_edges, weights=w_pi0_mc)
h_gam_dN_2_raw, _ = np.histogram(pt_g2_mc, bins=pt_edges, weights=w_pi0_mc)

h_gam_dN = mc_norm * (h_gam_dN_1_raw + h_gam_dN_2_raw)

# Convert dN/bin to invariant yield
pi0_inv_mc = h_pi0_dN / pt_widths / (2.0 * np.pi * pt_centers)
gam_pi0_decay_inv_mc = h_gam_dN / pt_widths / (2.0 * np.pi * pt_centers)

# Input pi0 invariant yield at same pT
pi0_inv_input = pi0_inv_spectrum(pt_centers)

# Missing factor:
# photons from pi0 decay / parent pi0 invariant yield
pi0_decay_gamma_over_pi0_parent = gam_pi0_decay_inv_mc / pi0_inv_input

print("MC norm =", mc_norm)
print("1 / MC norm =", 1.0 / mc_norm)

MC norm = 6.666666666666667e-06
1 / MC norm = 150000.0

In [18]:
df_pi0_decay_factor = pd.DataFrame({
    "pt": pt_centers,
    "pt_low": pt_edges[:-1],
    "pt_high": pt_edges[1:],
    "pi0_inv_input": pi0_inv_input,
    "pi0_inv_mc_check": pi0_inv_mc,
    "gamma_pi0_decay_inv": gam_pi0_decay_inv_mc,
    "gamma_pi0_decay_over_pi0_parent": pi0_decay_gamma_over_pi0_parent,
})

df_pi0_decay_factor

,pt,pt_low,pt_high,pi0_inv_input,pi0_inv_mc_check,gamma_pi0_decay_inv,gamma_pi0_decay_over_pi0_parent
0,0.90,0.8,1.0,1.993954e+00,2.074145e+00,1.199039e+00,0.601337
1,1.15,1.0,1.3,7.299405e-01,7.529106e-01,3.693396e-01,0.505986
2,1.50,1.3,1.7,1.927148e-01,2.071272e-01,8.658204e-02,0.449275
3,1.85,1.7,2.0,5.949864e-02,6.112142e-02,2.256124e-02,0.379189
4,2.25,2.0,2.5,1.723169e-02,1.843868e-02,6.090779e-03,0.353464
5,2.75,2.5,3.0,4.260105e-03,4.489834e-03,1.364473e-03,0.320291
6,3.50,3.0,4.0,6.675166e-04,8.049051e-04,2.309687e-04,0.346012
7,4.50,4.0,5.0,8.850276e-05,9.973226e-05,2.823335e-05,0.319011
8,6.00,5.0,7.0,8.707932e-06,1.128334e-05,3.192618e-06,0.366633
9,8.50,7.0,10.0,5.255632e-07,7.057186e-07,1.993944e-07,0.379392

In [19]:
import ROOT as root

g_factor = root.TGraph(len(df_pi0_decay_factor))

for i, row in enumerate(df_pi0_decay_factor.itertuples()):
    if row.gamma_pi0_decay_over_pi0_parent >1e30:
        continue
    g_factor.SetPoint(i, row.pt, row.gamma_pi0_decay_over_pi0_parent)

g_factor.SetTitle(";p_{T} (GeV/c);#gamma_{#pi^{0} decay} / #pi^{0}_{parent}")
g_factor.SetMarkerStyle(20)
g_factor.SetMarkerColor(root.kBlue)
g_factor.SetLineColor(root.kBlue)

c_factor = root.TCanvas("c_factor", "c_factor", 800, 600)
g_factor.Draw("AP")
c_factor.Draw()

In [20]:
def pi0_decay_gamma_over_pi0_parent_func(pt):
    return np.interp(
        pt,
        df_pi0_decay_factor["pt"].values,
        df_pi0_decay_factor["gamma_pi0_decay_over_pi0_parent"].values,
        left=np.nan,
        right=np.nan
    )

mask_rg = (
    np.isfinite(pt_arr) &
    np.isfinite(rgamma_arr) &
    np.isfinite(stat_arr) &
    np.isfinite(syst_down_arr) &
    np.isfinite(syst_up_arr) &
    (pt_arr >= pt_cuau_mb.min()) &
    (pt_arr <= pt_cuau_mb.max())
)

pt_dir = pt_arr[mask_rg]

Rgamma = rgamma_arr[mask_rg]
Rgamma_stat = stat_arr[mask_rg]
Rgamma_syst_down = syst_down_arr[mask_rg]
Rgamma_syst_up = syst_up_arr[mask_rg]

pi0_parent_inv = np.interp(pt_dir, pt_cuau_mb, y_cuau_mb)
pi0_parent_inv_stat = np.interp(pt_dir, pt_cuau_mb, y_cuau_mb_stat)
pi0_parent_inv_syst = np.interp(pt_dir, pt_cuau_mb, y_cuau_mb_syst)

pi0_to_gamma = np.array([pi0_decay_gamma_over_pi0_parent_func(pt) for pt in pt_dir])
decay_over_pi0gamma = np.array([gamma_hadron_over_gamma_pi0(pt) for pt in pt_dir])

gamma_pi0_decay_inv = pi0_to_gamma * pi0_parent_inv
gamma_pi0_decay_inv_stat = pi0_to_gamma * pi0_parent_inv_stat
gamma_pi0_decay_inv_syst = pi0_to_gamma * pi0_parent_inv_syst

gamma_decay_inv = decay_over_pi0gamma * gamma_pi0_decay_inv
gamma_decay_inv_stat = decay_over_pi0gamma * gamma_pi0_decay_inv_stat
gamma_decay_inv_syst = decay_over_pi0gamma * gamma_pi0_decay_inv_syst

gamma_direct_inv = (Rgamma - 1.0) * gamma_decay_inv

gamma_direct_inv_stat = np.sqrt(
    (gamma_decay_inv * Rgamma_stat)**2 +
    ((Rgamma - 1.0) * gamma_decay_inv_stat)**2
)

gamma_direct_inv_syst_down = np.sqrt(
    (gamma_decay_inv * Rgamma_syst_down)**2 +
    ((Rgamma - 1.0) * gamma_decay_inv_syst)**2
)

gamma_direct_inv_syst_up = np.sqrt(
    (gamma_decay_inv * Rgamma_syst_up)**2 +
    ((Rgamma - 1.0) * gamma_decay_inv_syst)**2
)

In [21]:
print(len(pt_dir), len(pt_edges[:-1]), len(pt_edges[1:]), len(gamma_direct_inv_syst_down), len(gamma_direct_inv_syst_up))

8 10 10 8 8

In [22]:
print(Rgamma_syst_up)

[0.67412331 0.67412331 0.67412331 0.67412331 0.67412331 0.67412331
 0.67412331 4.73339805]

In [23]:
df_direct_gamma = pd.DataFrame({
    "pt": pt_dir,

    "Rgamma": Rgamma,
    "Rgamma_stat": Rgamma_stat,
    "Rgamma_syst_down": Rgamma_syst_down,
    "Rgamma_syst_up": Rgamma_syst_up,

    "pi0_parent_inv": pi0_parent_inv,
    "pi0_to_gamma_decay_factor": pi0_to_gamma,
    "decay_over_pi0gamma": decay_over_pi0gamma,

    "gamma_pi0_decay_inv": gamma_pi0_decay_inv,
    "gamma_decay_inv": gamma_decay_inv,

    "gamma_direct": gamma_direct_inv,
    "gamma_direct_stat": gamma_direct_inv_stat,
    "gamma_direct_syst_down": gamma_direct_inv_syst_down,
    "gamma_direct_syst_up": gamma_direct_inv_syst_up,
})

for col in ["pt_low", "pt_high", "pt_err"]:
    df_direct_gamma[col] = np.nan

for i, row in df_direct_gamma.iterrows():
    m = df_rgamma_summary[np.isclose(df_rgamma_summary["pt"], row["pt"])]
    if len(m) > 0:
        df_direct_gamma.loc[i, "pt_low"] = m.iloc[0]["pt_low"]
        df_direct_gamma.loc[i, "pt_high"] = m.iloc[0]["pt_high"]
        df_direct_gamma.loc[i, "pt_err"] = m.iloc[0]["pt_err"]

# dN/dpT for integration
df_direct_gamma["gamma_direct_dndpt"] = 2.0 * np.pi * df_direct_gamma["pt"] * df_direct_gamma["gamma_direct"]
df_direct_gamma["gamma_direct_dndpt_stat"] = 2.0 * np.pi * df_direct_gamma["pt"] * df_direct_gamma["gamma_direct_stat"]
df_direct_gamma["gamma_direct_dndpt_syst_down"] = 2.0 * np.pi * df_direct_gamma["pt"] * df_direct_gamma["gamma_direct_syst_down"]
df_direct_gamma["gamma_direct_dndpt_syst_up"] = 2.0 * np.pi * df_direct_gamma["pt"] * df_direct_gamma["gamma_direct_syst_up"]

df_direct_gamma

,pt,Rgamma,Rgamma_stat,Rgamma_syst_down,Rgamma_syst_up,pi0_parent_inv,pi0_to_gamma_decay_factor,decay_over_pi0gamma,gamma_pi0_decay_inv,gamma_decay_inv,...,gamma_direct_stat,gamma_direct_syst_down,gamma_direct_syst_up,pt_low,pt_high,pt_err,gamma_direct_dndpt,gamma_direct_dndpt_stat,gamma_direct_dndpt_syst_down,gamma_direct_dndpt_syst_up
0,0.90,0.987284,0.021691,0.674123,0.674123,1.993954,0.601337,1.157730,1.199039,1.388163,...,0.030112,0.935794,0.935794,0.8,1.0,0.10,-0.099816,0.170277,5.291790,5.291790
1,1.15,1.113405,0.019663,0.674123,0.674123,0.729941,0.505986,1.170304,0.369340,0.432240,...,0.008538,0.291403,0.291403,1.0,1.3,0.15,0.354189,0.061691,2.105581,2.105581
2,1.50,1.035438,0.020411,0.674123,0.674123,0.192715,0.449275,1.184190,0.086582,0.102530,...,0.002093,0.069118,0.069118,1.3,1.7,0.20,0.034245,0.019730,0.651423,0.651423
3,1.85,1.013594,0.031071,0.674123,0.674123,0.059499,0.379189,1.193610,0.022561,0.026929,...,0.000837,0.018154,0.018154,1.7,2.0,0.15,0.004255,0.009726,0.211017,0.211017
4,2.25,1.071789,0.036423,0.674123,0.674123,0.017232,0.353464,1.201840,0.006091,0.007320,...,0.000267,0.004935,0.004935,2.0,2.5,0.25,0.007429,0.003770,0.069765,0.069765
5,2.75,1.015669,0.054232,0.674123,0.674123,0.004260,0.320291,1.209260,0.001364,0.001650,...,0.000089,0.001112,0.001112,2.5,3.0,0.25,0.000447,0.001546,0.019219,0.019219
6,3.50,1.154578,0.087071,0.674123,0.674123,0.000668,0.346012,1.217080,0.000231,0.000281,...,0.000024,0.000190,0.000190,3.0,4.0,0.50,0.000956,0.000538,0.004168,0.004168
7,4.50,2.963092,1.137719,0.877021,4.733398,0.000089,0.319011,1.223650,0.000028,0.000035,...,0.000039,0.000031,0.000164,4.0,5.0,0.50,0.001918,0.001111,0.000874,0.004627

In [24]:
import numpy as np
import pandas as pd

mask_rg = (
    np.isfinite(pt_arr) &
    np.isfinite(rgamma_arr) &
    np.isfinite(stat_arr) &
    np.isfinite(syst_down_arr) &
    np.isfinite(syst_up_arr) &
    (pt_arr >= pt_cuau_mb.min()) &
    (pt_arr <= pt_cuau_mb.max())
)

pt_dir = pt_arr[mask_rg]

Rgamma = rgamma_arr[mask_rg]
Rgamma_stat = stat_arr[mask_rg]
Rgamma_syst_down = syst_down_arr[mask_rg]
Rgamma_syst_up = syst_up_arr[mask_rg]

# Same-pT approximation for pi0-decay photon denominator used in the double-ratio method
pi0_gamma_inv = np.interp(pt_dir, pt_cuau_mb, y_cuau_mb)
pi0_gamma_inv_stat = np.interp(pt_dir, pt_cuau_mb, y_cuau_mb_stat)
pi0_gamma_inv_syst = np.interp(pt_dir, pt_cuau_mb, y_cuau_mb_syst)

# MC cocktail ratio: all decay photons / pi0-decay photons
decay_over_pi0gamma = np.array([gamma_hadron_over_gamma_pi0(pt) for pt in pt_dir])

gamma_decay_inv = decay_over_pi0gamma * pi0_gamma_inv
gamma_decay_inv_stat = decay_over_pi0gamma * pi0_gamma_inv_stat
gamma_decay_inv_syst = decay_over_pi0gamma * pi0_gamma_inv_syst

gamma_direct_inv = (Rgamma - 1.0) * gamma_decay_inv

gamma_direct_inv_stat = np.sqrt(
    (gamma_decay_inv * Rgamma_stat)**2 +
    ((Rgamma - 1.0) * gamma_decay_inv_stat)**2
)

gamma_direct_inv_syst_down = np.sqrt(
    (gamma_decay_inv * Rgamma_syst_down)**2 +
    ((Rgamma - 1.0) * gamma_decay_inv_syst)**2
)

gamma_direct_inv_syst_up = np.sqrt(
    (gamma_decay_inv * Rgamma_syst_up)**2 +
    ((Rgamma - 1.0) * gamma_decay_inv_syst)**2
)

gamma_direct_dndpt = 2.0 * np.pi * pt_dir * gamma_direct_inv
gamma_direct_dndpt_stat = 2.0 * np.pi * pt_dir * gamma_direct_inv_stat
gamma_direct_dndpt_syst_down = 2.0 * np.pi * pt_dir * gamma_direct_inv_syst_down
gamma_direct_dndpt_syst_up = 2.0 * np.pi * pt_dir * gamma_direct_inv_syst_up

df_direct_gamma_old = pd.DataFrame({
    "pt": pt_dir,

    "Rgamma": Rgamma,
    "Rgamma_stat": Rgamma_stat,
    "Rgamma_syst_down": Rgamma_syst_down,
    "Rgamma_syst_up": Rgamma_syst_up,

    "pi0_gamma_inv": pi0_gamma_inv,
    "pi0_gamma_inv_stat": pi0_gamma_inv_stat,
    "pi0_gamma_inv_syst": pi0_gamma_inv_syst,

    "decay_over_pi0gamma": decay_over_pi0gamma,
    "gamma_decay_inv": gamma_decay_inv,

    "gamma_direct": gamma_direct_inv,
    "gamma_direct_stat": gamma_direct_inv_stat,
    "gamma_direct_syst_down": gamma_direct_inv_syst_down,
    "gamma_direct_syst_up": gamma_direct_inv_syst_up,

    "gamma_direct_dndpt": gamma_direct_dndpt,
    "gamma_direct_dndpt_stat": gamma_direct_dndpt_stat,
    "gamma_direct_dndpt_syst_down": gamma_direct_dndpt_syst_down,
    "gamma_direct_dndpt_syst_up": gamma_direct_dndpt_syst_up,
})

# Make sure all relevant columns are numeric
for col in ["pt", "pt_low", "pt_high", "pt_err"]:
    df_rgamma_summary[col] = pd.to_numeric(df_rgamma_summary[col], errors="coerce")

# Robust merge instead of floating-point matching
df_edges = df_rgamma_summary[["pt", "pt_low", "pt_high", "pt_err"]].copy()
df_edges["pt_key"] = df_edges["pt"].round(6)

df_direct_gamma["pt_key"] = df_direct_gamma["pt"].round(6)

df_direct_gamma = df_direct_gamma.drop(
    columns=[c for c in ["pt_low", "pt_high", "pt_err"] if c in df_direct_gamma.columns]
)

df_direct_gamma = df_direct_gamma.merge(
    df_edges[["pt_key", "pt_low", "pt_high", "pt_err"]],
    on="pt_key",
    how="left"
)

df_direct_gamma = df_direct_gamma.drop(columns=["pt_key"])

df_direct_gamma_old

,pt,Rgamma,Rgamma_stat,Rgamma_syst_down,Rgamma_syst_up,pi0_gamma_inv,pi0_gamma_inv_stat,pi0_gamma_inv_syst,decay_over_pi0gamma,gamma_decay_inv,gamma_direct,gamma_direct_stat,gamma_direct_syst_down,gamma_direct_syst_up,gamma_direct_dndpt,gamma_direct_dndpt_stat,gamma_direct_dndpt_syst_down,gamma_direct_dndpt_syst_up
0,0.90,0.987284,0.021691,0.674123,0.674123,1.993954,3.297918e-02,0.140184,1.157730,2.308460,-0.029354,0.050074,1.556188,1.556188,-0.165991,0.283164,8.800037,8.800037
1,1.15,1.113405,0.019663,0.674123,0.674123,0.729941,1.207292e-02,0.051318,1.170304,0.854252,0.096877,0.016873,0.575912,0.575912,0.699998,0.121922,4.161344,4.161344
2,1.50,1.035438,0.020411,0.674123,0.674123,0.192715,2.779914e-03,0.013882,1.184190,0.228211,0.008087,0.004660,0.153843,0.153843,0.076222,0.043915,1.449940,1.449940
3,1.85,1.013594,0.031071,0.674123,0.674123,0.059499,7.113188e-04,0.004439,1.193610,0.071018,0.000965,0.002207,0.047875,0.047875,0.011222,0.025649,0.556495,0.556495
4,2.25,1.071789,0.036423,0.674123,0.674123,0.017232,1.801725e-04,0.001346,1.201840,0.020710,0.001487,0.000754,0.013961,0.013961,0.021018,0.010666,0.197375,0.197375
5,2.75,1.015669,0.054232,0.674123,0.674123,0.004260,4.092407e-05,0.000335,1.209260,0.005152,0.000081,0.000279,0.003473,0.003473,0.001395,0.004827,0.060006,0.060006
6,3.50,1.154578,0.087071,0.674123,0.674123,0.000668,5.846780e-06,0.000058,1.217080,0.000812,0.000126,0.000071,0.000548,0.000548,0.002762,0.001556,0.012046,0.012046
7,4.50,2.963092,1.137719,0.877021,4.733398,0.000089,7.302823e-07,0.000008,1.223650,0.000108,0.000213,0.000123,0.000097,0.000513,0.006011,0.003484,0.002740,0.014504

In [25]:
g_dir_stat = root.TGraphErrors(len(df_direct_gamma))
g_dir_syst = root.TGraphAsymmErrors(len(df_direct_gamma))

for i, row in enumerate(df_direct_gamma.itertuples()):
    pt = row.pt
    y = row.gamma_direct

    # use bin half-width if available, otherwise small visual width
    ex = getattr(row, "pt_err", 0.0)/2
    if ex == 0.0:
        ex = 0.05

    # stat graph
    g_dir_stat.SetPoint(i, pt, y)
    g_dir_stat.SetPointError(i, 0.0, row.gamma_direct_stat)

    # syst box/band
    g_dir_syst.SetPoint(i, pt, y)
    g_dir_syst.SetPointError(
        i,
        ex, ex,
        row.gamma_direct_syst_down,
        row.gamma_direct_syst_up
    )

In [26]:
pt_cuau = np.array([0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.25, 2.75, 3.25, 3.75, 4.5, 6.0, 8.5])

y_cuau_30_40 = np.array([3.573e-01, 1.457e-01, 6.346e-02, 2.928e-02, 1.363e-02, 8.574e-03, 3.011e-03, 6.748e-04, 2.120e-04, 7.667e-05, 2.077e-05, 2.396e-06, 2.447e-07])
y_cuau_30_40_stat = np.array([4.882e-02, 1.485e-02, 6.090e-03, 2.845e-03, 1.414e-03, 8.174e-04, 2.282e-04, 7.173e-05, 2.983e-05, 1.386e-05, 3.162e-06, 4.530e-07, 7.317e-08])
y_cuau_30_40_syst = np.array([1.361e-01, 5.284e-02, 2.226e-02, 9.913e-03, 4.582e-03, 2.347e-03, 7.732e-04, 1.769e-04, 5.119e-05, 1.737e-05, 4.492e-06, 5.210e-07, 5.609e-08])

y_cuau_40_50 = np.array([1.785e-01, 8.562e-02, 3.786e-02, 1.798e-02, 7.225e-03, 3.809e-03, 1.445e-03, 4.402e-04, 1.170e-04, 5.412e-05, 1.214e-05, 1.503e-06, 1.037e-07])
y_cuau_40_50_stat = np.array([2.674e-02, 8.298e-03, 3.393e-03, 1.642e-03, 8.086e-04, 4.485e-04, 1.263e-04, 4.555e-05, 1.830e-05, 9.488e-06, 2.098e-06, 3.014e-07, 3.870e-08])
y_cuau_40_50_syst = np.array([8.115e-02, 3.212e-02, 1.345e-02, 6.122e-03, 2.781e-03, 1.369e-03, 4.507e-04, 1.142e-04, 3.097e-05, 1.191e-05, 2.718e-06, 3.318e-07, 2.463e-08])

gr_4050 = root.TGraphErrors(len(pt_cuau), pt_cuau, y_cuau_40_50, np.zeros_like(pt_cuau), y_cuau_40_50_stat)
gr_4050.SetMarkerStyle(20)
gr_4050.SetMarkerSize(1.2)
gr_4050.SetMarkerColor(root.kRed)
gr_4050.SetLineColor(root.kRed)

gr_4050_syst = root.TGraphAsymmErrors(len(pt_cuau))
for i in range(len(pt_cuau)):
    gr_4050_syst.SetPoint(i, pt_cuau[i], y_cuau_40_50[i])
    gr_4050_syst.SetPointError(
        i,
        0.05, 0.05,  # x error (fixed width)
        y_cuau_40_50_syst[i], y_cuau_40_50_syst[i]  # symmetric y error
    )
gr_4050_syst.SetFillColor(root.kRed - 10)
gr_4050_syst.SetLineColor(root.kRed - 10)

In [27]:


c_dir = root.TCanvas("c_dir", "c_dir", 800, 600)
c_dir.SetLogy()

g_dir_stat.SetName("g_direct_gamma_stat")
Format_Hist_total(g_dir_stat, title_x="p_{T} [GeV/c]",  title_y="d^{2}N_{#gamma}^{dir}/(2#pip_{T}dp_{T}d#eta)", left=0.15, bottom=0.15, right=0.01, top=0.01,  Tsize=0.06,  Lsize=0.06,\
                      Mstyle=21,  Msize=1.2, Mcolor=4,  Lwidth=3,  Lcolor=4,  offset_x=1, offset_y=1.1, title="",  Malpha=0.5,  Lalpha=1)

g_dir_syst.SetName("g_direct_gamma_syst")
g_dir_syst.SetFillColorAlpha(root.kBlue, 0.25)
g_dir_syst.SetLineColor(root.kBlue)
g_dir_syst.SetMarkerColor(root.kBlue)

g_dir_stat.Draw("AP")
g_dir_stat.GetYaxis().SetRangeUser(1e-7, 4e-1)
g_dir_stat.GetXaxis().SetRangeUser(0, 7)

gr_4050_syst.Draw("2 same")
gr_4050.Draw("P same")

g_dir_syst.Draw("2 same")
g_dir_stat.Draw("P same")


legend0 = root.TLegend(0.34, 0.88, 0.94, 0.96,"0%-93% Cu+Au")
legend0.SetTextAlign(32)
legend0.SetBorderSize(0)
legend0.SetFillStyle(0)
legend0.SetTextSize(0.06)
legend0.Draw()
legend3 = root.TLegend(0.34, 0.80, 0.94, 0.88,"#sqrt{s_{NN}} = 200 GeV")
legend3.SetTextAlign(32)
legend3.SetBorderSize(0)
legend3.SetFillStyle(0)
legend3.SetTextSize(0.06)
legend3.Draw()
legend2 = root.TLegend(0.79, 0.72, 0.94, 0.80,"|#eta|<0.35")
legend2.SetTextAlign(32)
legend2.SetBorderSize(0)
legend2.SetFillStyle(0)
legend2.SetTextSize(0.06)
legend2.Draw()
legend1 = root.TLegend(0.16, 0.17, 0.4, 0.35)
legend1.SetBorderSize(0)
legend1.SetFillStyle(0)
#legend1.SetNColumns(2)
legend1.SetTextSize(0.06)
legend1.AddEntry(g_dir_stat, "0%-93% Cu+Au: dN_{ch}/d#eta #approx 102","p")
if draw_ppg243:
    legend1.AddEntry(gr_4050, "40%-50% AuAu: dN_{ch}/d#eta #approx 107", "p")
legend1.Draw()

leg5 = root.TLegend(0.77, 0.18, 0.99, 0.25,"PRC109 044912")
leg5.SetBorderSize(0)
leg5.SetFillStyle(0)
leg5.SetTextSize(0.040)
leg5.Draw()

c_dir.Draw()

if safe_to_pdf: 
    c_dir.SaveAs("output/res/spectrum_stat_syst.pdf")

In [28]:
c_dir.Draw()

In [29]:
import numpy as np
import ROOT as root

# ------------------------------------------------------------
# p+p direct photon fit from PRC 109, 044912
# d^3N / d^2pT dy = A_pp / (1 + (pT/p0)^2)^n
# This has the same units as invariant yield:
# (1 / 2pi pT) d^2N / dpT dy
# ------------------------------------------------------------

A_pp = 1.60e-4          # (GeV/c)^-2
p0_pp = 1.45            # GeV/c
n_pp = 3.3

def pp_direct_gamma_fit(pt, A=A_pp, p0=p0_pp, n=n_pp):
    pt = np.asarray(pt, dtype=float)
    return A / (1.0 + (pt / p0)**2)**n


# ------------------------------------------------------------
# Ncoll scaling
# Replace this with the Cu+Au MB <Ncoll> value you want to use.
# ------------------------------------------------------------

Ncoll_cuau_mb = 108.0     # TODO: replace with Cu+Au MB <Ncoll>
Ncoll_rel_unc = .1     # optional, e.g. 0.08 for 8% Ncoll uncertainty


# ------------------------------------------------------------
# Uncertainty band
#
# The PRC paper says the band includes uncertainty from the p+p data
# and the unknown true low-pT functional form.
#
# If you do not have the published numerical band, use a relative
# uncertainty function here. You can tune it.
# ------------------------------------------------------------

def pp_fit_rel_unc(pt):
    pt = np.asarray(pt, dtype=float)

    # Example shape:
    # larger uncertainty below 2 GeV/c,
    # smaller uncertainty at high pT.
    rel = 0.7/pt+0.1

    return rel


# ------------------------------------------------------------
# Build smooth TGraph and TGraphAsymmErrors band
# ------------------------------------------------------------

pt_min = 0.8
pt_max = 7.0
n_points = 300

pt_grid = np.linspace(pt_min, pt_max, n_points)

y_pp = pp_direct_gamma_fit(pt_grid)
y_scaled = Ncoll_cuau_mb * y_pp

rel_pp = pp_fit_rel_unc(pt_grid)

# combine p+p fit uncertainty and Ncoll uncertainty
rel_total = np.sqrt(rel_pp**2 + Ncoll_rel_unc**2)

y_low = y_scaled * (1.0 - rel_total)
y_high = y_scaled * (1.0 + rel_total)

# protect log scale
y_low = np.maximum(y_low, 1e-30)

g_pp_scaled = root.TGraph(n_points)
g_pp_scaled_band = root.TGraphAsymmErrors(n_points)

for i, (pt, y, yl, yh) in enumerate(zip(pt_grid, y_scaled, y_low, y_high)):
    g_pp_scaled.SetPoint(i, float(pt), float(y))

    g_pp_scaled_band.SetPoint(i, float(pt), float(y))
    g_pp_scaled_band.SetPointError(
        i,
        0.0,
        0.0,
        float(y - yl),
        float(yh - y)
    )

g_pp_scaled.SetName("g_pp_scaled_fit")
g_pp_scaled_band.SetName("g_pp_scaled_fit_band")

# Orange style similar to paper
g_pp_scaled.SetLineColor(root.kOrange + 7)
g_pp_scaled.SetLineWidth(3)
g_pp_scaled.SetFillColorAlpha(root.kOrange + 7, 0.25)

g_pp_scaled_band.SetFillColorAlpha(root.kOrange + 7, 0.25)
g_pp_scaled_band.SetLineColor(root.kOrange + 7)
g_pp_scaled_band.SetLineWidth(1)


# ------------------------------------------------------------
# Optional draw example
# ------------------------------------------------------------
# Draw band first, then line, then your data points.
#
# g_pp_scaled_band.Draw("3 same")
# g_pp_scaled.Draw("L same")

In [30]:


c_dir1 = root.TCanvas("c_dir1", "c_dir1", 800, 600)
c_dir1.SetLogy()

g_dir_stat.SetName("g_direct_gamma_stat")
Format_Hist_total(g_dir_stat, title_x="p_{T} [GeV/c]",  title_y="d^{2}N_{#gamma}^{dir}/(2#pip_{T}dp_{T}d#eta)", left=0.15, bottom=0.15, right=0.01, top=0.01,  Tsize=0.06,  Lsize=0.06,\
                      Mstyle=21,  Msize=1.2, Mcolor=4,  Lwidth=3,  Lcolor=4,  offset_x=1, offset_y=1.1, title="",  Malpha=0.5,  Lalpha=1)

g_dir_syst.SetName("g_direct_gamma_syst")
g_dir_syst.SetFillColorAlpha(root.kBlue, 0.25)
g_dir_syst.SetLineColor(root.kBlue)
g_dir_syst.SetMarkerColor(root.kBlue)

g_dir_stat.Draw("AP")
g_dir_stat.GetYaxis().SetRangeUser(1e-7, 4e-1)
g_dir_stat.GetXaxis().SetRangeUser(0, 7)


g_dir_syst.Draw("2 same")
g_dir_stat.Draw("P same")

g_pp_scaled_band.Draw("3 same")
g_pp_scaled.Draw("L same")


legend0 = root.TLegend(0.34, 0.88, 0.94, 0.96,"0%-93% Cu+Au")
legend0.SetTextAlign(32)
legend0.SetBorderSize(0)
legend0.SetFillStyle(0)
legend0.SetTextSize(0.06)
legend0.Draw()
legend3 = root.TLegend(0.34, 0.80, 0.94, 0.88,"#sqrt{s_{NN}} = 200 GeV")
legend3.SetTextAlign(32)
legend3.SetBorderSize(0)
legend3.SetFillStyle(0)
legend3.SetTextSize(0.06)
legend3.Draw()
legend2 = root.TLegend(0.79, 0.72, 0.94, 0.80,"|#eta|<0.35")
legend2.SetTextAlign(32)
legend2.SetBorderSize(0)
legend2.SetFillStyle(0)
legend2.SetTextSize(0.06)
legend2.Draw()
legend1 = root.TLegend(0.17, 0.19, 0.4, 0.44)
legend1.SetBorderSize(0)
legend1.SetFillStyle(0)
#legend1.SetNColumns(2)
legend1.SetTextSize(0.06)
legend1.AddEntry(g_dir_stat, "0%-93% Cu+Au","p")
legend1.AddEntry(g_pp_scaled, "N_{coll} scaled pp fit: #frac{A_{pp}}{[1 + (p_{T}/p_{0})^{2}]^{n}}","fl")
#legend1.AddEntry(g_pp_scaled_band, "p+p direct photon fit uncertainty","f")
legend1.Draw()


c_dir1.Draw()

if safe_to_pdf: 
    c_dir1.SaveAs("output/res/spectrum_stat_syst1.pdf")

In [31]:
c_dir1.Draw()

In [32]:
print("pt_direct =", df_direct_gamma["pt"].values.tolist())
print("direct_gamma =", df_direct_gamma["gamma_direct"].values.tolist())
print("direct_gamma_stat =", df_direct_gamma["gamma_direct_stat"].values.tolist())
print("direct_gamma_syst_down =", df_direct_gamma["gamma_direct_syst_down"].values.tolist())
print("direct_gamma_syst_up =", df_direct_gamma["gamma_direct_syst_up"].values.tolist())

pt_direct = [0.9, 1.15, 1.5, 1.85, 2.25, 2.75, 3.5, 4.5]
direct_gamma = [-0.017651404473651336, 0.04901823427609726, 0.0036334599845348724, 0.0003660665984754736, 0.000525507214210428, 2.5853938862871e-05, 4.3453099396319794e-05, 6.78203795064437e-05]
direct_gamma_stat = [0.030111595114492472, 0.008537714191191374, 0.0020934076621443773, 0.0008367189863858866, 0.00026667596559511295, 8.94826520288382e-05, 2.447919512905538e-05, 3.930960837555946e-05]
direct_gamma_syst_down = [0.9357939855541121, 0.29140314665997485, 0.0691180801947373, 0.018153700073743385, 0.004934849198476287, 0.001112307126732693, 0.00018953878558356763, 3.091049870216889e-05]
direct_gamma_syst_up = [0.9357939855541121, 0.29140314665997485, 0.0691180801947373, 0.018153700073743385, 0.004934849198476287, 0.001112307126732693, 0.00018953878558356763, 0.00016364259755506695]

In [33]:
dNch_cuau_mb = np.array([623.9, 414.2, 274.0, 176.8, 109.4, 61.6, 32.0, 15.5])

y_cuau_mb = np.array([1.250e+00, 9.956e-01, 7.202e-01, 4.549e-01, 2.626e-01, 1.358e-01, 5.746e-02, 2.700e-02])

y_cuau_mb_stat = np.array([1.594e-01, 8.483e-02, 3.902e-02, 2.554e-02, 1.433e-02, 7.254e-03, 3.696e-03, 1.880e-03])

y_cuau_mb_syst = np.array([5.212e-01, 3.510e-01, 2.360e-01, 1.556e-01, 9.418e-02, 5.193e-02, 2.455e-02, 1.054e-02])

In [34]:
# pT bin edges are now attached directly in the df_direct_gamma construction cell.
df_direct_gamma[["pt", "pt_low", "pt_high", "pt_err", "gamma_direct", "gamma_direct_dndpt", "gamma_direct_stat", "gamma_direct_syst_down", "gamma_direct_syst_up"]]

,pt,pt_low,pt_high,pt_err,gamma_direct,gamma_direct_dndpt,gamma_direct_stat,gamma_direct_syst_down,gamma_direct_syst_up
0,0.90,0.8,1.0,0.10,-0.017651,-0.099816,0.030112,0.935794,0.935794
1,1.15,1.0,1.3,0.15,0.049018,0.354189,0.008538,0.291403,0.291403
2,1.50,1.3,1.7,0.20,0.003633,0.034245,0.002093,0.069118,0.069118
3,1.85,1.7,2.0,0.15,0.000366,0.004255,0.000837,0.018154,0.018154
4,2.25,2.0,2.5,0.25,0.000526,0.007429,0.000267,0.004935,0.004935
5,2.75,2.5,3.0,0.25,0.000026,0.000447,0.000089,0.001112,0.001112
6,3.50,3.0,4.0,0.50,0.000043,0.000956,0.000024,0.000190,0.000190
7,4.50,4.0,5.0,0.50,0.000068,0.001918,0.000039,0.000031,0.000164

In [35]:
def integrate_dndy_from_invariant_yield(df, pt_min=1.0, pt_max=5.0):
    dNdy = 0.0
    stat2 = 0.0
    syst_down2 = 0.0
    syst_up2 = 0.0
    rows_used = []

    for row in df.itertuples():
        if not np.isfinite(row.gamma_direct):
            continue
        if not np.isfinite(row.pt_low) or not np.isfinite(row.pt_high):
            continue

        lo = max(row.pt_low, pt_min)
        hi = min(row.pt_high, pt_max)
        if hi <= lo:
            continue

        width = hi - lo
        weight = 2.0 * np.pi * row.pt * width
        val = weight * row.gamma_direct
        stat = weight * row.gamma_direct_stat
        syst_down = weight * row.gamma_direct_syst_down
        syst_up = weight * row.gamma_direct_syst_up
        print(f"pt: {row.pt}, val: {val}, stat: {stat}, syst_down: {syst_down}, syst_up: {syst_up}")

        dNdy += val
        stat2 += stat
        syst_down2 += syst_down
        syst_up2 += syst_up
        #stat2 += stat**2
        #syst_down2 += syst_down**2
        #syst_up2 += syst_up**2

        rows_used.append({
            "pt": row.pt,
            "pt_low_used": lo,
            "pt_high_used": hi,
            "width_used": width,
            "gamma_direct_inv": row.gamma_direct,
            "contribution": val,
            "stat_contribution": stat,
            "syst_down_contribution": syst_down,
            "syst_up_contribution": syst_up,
        })

    return {
        "dNdy": dNdy,
        "stat": (stat2),
        "syst_down": (syst_down2),
        "syst_up": (syst_up2),
        #"stat": np.sqrt(stat2),
        #"syst_down": np.sqrt(syst_down2),
        #"syst_up": np.sqrt(syst_up2),
        "rows_used": pd.DataFrame(rows_used),
    }

In [36]:
res_dndy_1_5 = integrate_dndy_from_invariant_yield(
    df_direct_gamma,
    pt_min=1.0,
    pt_max=5.0
)

print("dN/dy direct gamma, 1<pT<5:")
print("value     =", res_dndy_1_5["dNdy"])
print("stat      =", res_dndy_1_5["stat"])
print("syst_down =", res_dndy_1_5["syst_down"])
print("syst_up   =", res_dndy_1_5["syst_up"])

res_dndy_1_5["rows_used"]

pt: 1.15, val: 0.10625677403867399, stat: 0.018507193925232323, syst_down: 0.6316742894981485, syst_up: 0.6316742894981485
pt: 1.5, val: 0.013697821433432683, stat: 0.007891960958833629, syst_down: 0.2605690235640202, syst_up: 0.2605690235640202
pt: 1.85, val: 0.0012765356715096186, stat: 0.0029177795450313878, syst_down: 0.06330499917373059, syst_up: 0.06330499917373059
pt: 2.25, val: 0.003714591608036816, stat: 0.0018850213224057854, syst_down: 0.034882393474139815, syst_up: 0.034882393474139815
pt: 2.75, val: 0.00022336199709437673, stat: 0.0007730746161532071, syst_down: 0.009609643719167248, syst_up: 0.009609643719167248
pt: 3.5, val: 0.0009555835648742974, stat: 0.00053832561708262, syst_down: 0.004168175594517669, syst_up: 0.004168175594517669
pt: 4.5, val: 0.0019175760541900375, stat: 0.0011114529919933446, syst_down: 0.0008739737607737756, syst_up: 0.004626885440640145
dN/dy direct gamma, 1<pT<5:
value     = 0.12804224436781184
stat      = 0.033624808976732305
syst_down = 1.0050824987844977
syst_up   = 1.0088354104643642

,pt,pt_low_used,pt_high_used,width_used,gamma_direct_inv,contribution,stat_contribution,syst_down_contribution,syst_up_contribution
0,1.15,1.0,1.3,0.3,0.049018,0.106257,0.018507,0.631674,0.631674
1,1.50,1.3,1.7,0.4,0.003633,0.013698,0.007892,0.260569,0.260569
2,1.85,1.7,2.0,0.3,0.000366,0.001277,0.002918,0.063305,0.063305
3,2.25,2.0,2.5,0.5,0.000526,0.003715,0.001885,0.034882,0.034882
4,2.75,2.5,3.0,0.5,0.000026,0.000223,0.000773,0.009610,0.009610
5,3.50,3.0,4.0,1.0,0.000043,0.000956,0.000538,0.004168,0.004168
6,4.50,4.0,5.0,1.0,0.000068,0.001918,0.001111,0.000874,0.004627

In [37]:
pt_dndy = 3.0
pt_dndy_err = 2.0

dndy = res_dndy_1_5["dNdy"]
dndy_stat = res_dndy_1_5["stat"]
dndy_syst_down = res_dndy_1_5["syst_down"]
dndy_syst_up = res_dndy_1_5["syst_up"]

print("pt_dndy =", pt_dndy)
print("pt_dndy_err =", pt_dndy_err)
print("dndy =", dndy)
print("dndy_stat =", dndy_stat)
print("dndy_syst_down =", dndy_syst_down)
print("dndy_syst_up =", dndy_syst_up)

pt_dndy = 3.0
pt_dndy_err = 2.0
dndy = 0.12804224436781184
dndy_stat = 0.033624808976732305
dndy_syst_down = 1.0050824987844977
dndy_syst_up = 1.0088354104643642

In [38]:
import ROOT as root
import numpy as np

# Existing Au+Au centrality-dependent points
dNch_auau = np.array([623.9, 414.2, 274.0, 176.8, 109.4, 61.6, 32.0, 15.5])

y_auau = np.array([1.250e+00, 9.956e-01, 7.202e-01, 4.549e-01,
                   2.626e-01, 1.358e-01, 5.746e-02, 2.700e-02])

y_auau_stat = np.array([1.594e-01, 8.483e-02, 3.902e-02, 2.554e-02,
                        1.433e-02, 7.254e-03, 3.696e-03, 1.880e-03])

y_auau_syst = np.array([5.212e-01, 3.510e-01, 2.360e-01, 1.556e-01,
                        9.418e-02, 5.193e-02, 2.455e-02, 1.054e-02])

# Your extracted MB point
dNch_mb = 100.0
dNch_mb_err = 15.0

dndy_mb = res_dndy_1_5["dNdy"]
dndy_mb_stat = res_dndy_1_5["stat"]
dndy_mb_syst_down = res_dndy_1_5["syst_down"]
dndy_mb_syst_up = res_dndy_1_5["syst_up"]

print("MB point:")
print("dNch =", dNch_mb, "+/-", dNch_mb_err)
print("dN/dy =", dndy_mb)
print("stat =", dndy_mb_stat)
print("syst_down =", dndy_mb_syst_down)
print("syst_up =", dndy_mb_syst_up)

MB point:
dNch = 100.0 +/- 15.0
dN/dy = 0.12804224436781184
stat = 0.033624808976732305
syst_down = 1.0050824987844977
syst_up = 1.0088354104643642

In [39]:
# Existing points: stat graph
g_auau_stat = root.TGraphErrors(len(dNch_auau))

# Existing points: syst boxes
g_auau_syst = root.TGraphErrors(len(dNch_auau))

for i in range(len(dNch_auau)):
    g_auau_stat.SetPoint(i, dNch_auau[i], y_auau[i])
    g_auau_stat.SetPointError(i, 0.0, y_auau_stat[i])

    g_auau_syst.SetPoint(i, dNch_auau[i], y_auau[i])
    g_auau_syst.SetPointError(i, dNch_auau[i]*0.05, y_auau_syst[i])


# Your MB point: stat
g_mb_stat = root.TGraphErrors(1)
g_mb_stat.SetPoint(0, dNch_mb, dndy_mb)
g_mb_stat.SetPointError(0, 0.0, dndy_mb_stat)

# Your MB point: asymmetric syst box, including x uncertainty from dNch
g_mb_syst = root.TGraphAsymmErrors(1)
g_mb_syst.SetPoint(0, dNch_mb, dndy_mb)
g_mb_syst.SetPointError(
    0,
    dNch_mb_err, dNch_mb_err,
    dndy_mb_syst_down, dndy_mb_syst_up
)

In [40]:
c_dndy_vs_dNch = root.TCanvas("c_dndy_vs_dNch", "c_dndy_vs_dNch", 850, 700)
c_dndy_vs_dNch.SetLogy()

frame = root.TH2F(
    "frame_dndy_vs_dNch",
    ";dN_{ch}/d#eta;dN_{#gamma}^{dir}/dy, 1<p_{T}<5 GeV/c",
    100, 1e1, 2e3,
    100, 1e-2, 3.0
)
frame.SetStats(0)
frame.Draw()
root.gPad.SetLogy()
root.gPad.SetLogx()
# Existing Au+Au syst
g_auau_syst.SetFillColorAlpha(root.kBlack, 0.35)
g_auau_syst.SetLineColor(root.kGray + 2)
g_auau_syst.Draw("2 same")

# Existing Au+Au stat
g_auau_stat.SetMarkerStyle(20)
g_auau_stat.SetMarkerSize(1.2)
g_auau_stat.SetMarkerColor(root.kBlack)
g_auau_stat.SetLineColor(root.kBlack)
g_auau_stat.Draw("P same")

# MB point syst
g_mb_syst.SetFillColorAlpha(root.kRed, 0.30)
g_mb_syst.SetLineColor(root.kRed)
g_mb_syst.Draw("2 same")

# MB point stat
g_mb_stat.SetMarkerStyle(29)
g_mb_stat.SetMarkerSize(2.0)
g_mb_stat.SetMarkerColor(root.kRed)
g_mb_stat.SetLineColor(root.kRed)
g_mb_stat.Draw("P same")

leg = root.TLegend(0.16, 0.70, 0.55, 0.88)
leg.SetBorderSize(0)
leg.SetFillStyle(0)
leg.SetTextSize(0.035)
leg.AddEntry(g_auau_stat, "Au+Au centrality points", "p")
leg.AddEntry(g_auau_syst, "Au+Au syst.", "f")
leg.AddEntry(g_mb_stat, "This analysis MB", "p")
leg.AddEntry(g_mb_syst, "This analysis MB syst.", "f")
leg.Draw()

c_dndy_vs_dNch.Draw()
#c_dndy_vs_dNch.SaveAs("output/direct_gamma_dndy_vs_dNch.png")
#c_dndy_vs_dNch.SaveAs("output/direct_gamma_dndy_vs_dNch.pdf")

In [41]:
import os
import pandas as pd
import numpy as np

os.makedirs("output/final_integrated", exist_ok=True)

# Choose the pT integration range used here
pt_int_min = 1.0
pt_int_max = 5.0

# Your MB charged multiplicit

df_mb_integrated = pd.DataFrame([{
    "system": "CuAu",
    "label": "This analysis MB",
    "pt_min": pt_int_min,
    "pt_max": pt_int_max,

    "dNch": dNch_mb,
    "dNch_err": dNch_mb_err,

    "dNdy": res_dndy_1_5["dNdy"],
    "dNdy_stat": res_dndy_1_5["stat"],
    "dNdy_syst_down": res_dndy_1_5["syst_down"],
    "dNdy_syst_up": res_dndy_1_5["syst_up"],
}])

df_mb_integrated.to_csv(
    "output/final_integrated/cuau_mb_direct_gamma_dndy_1_5.csv",
    index=False
)

df_mb_integrated

,system,label,pt_min,pt_max,dNch,dNch_err,dNdy,dNdy_stat,dNdy_syst_down,dNdy_syst_up
0,CuAu,This analysis MB,1.0,5.0,100.0,15.0,0.128042,0.033625,1.005082,1.008835

In [42]:
res_dndy_15_5 = integrate_dndy_from_invariant_yield(
    df_direct_gamma,
    pt_min=1.5,
    pt_max=5.0
)

df_mb_integrated_15_5 = pd.DataFrame([{
    "system": "CuAu",
    "label": "This analysis MB",
    "pt_min": 1.5,
    "pt_max": 5.0,

    "dNch": dNch_mb,
    "dNch_err": dNch_mb_err,

    "dNdy": res_dndy_15_5["dNdy"],
    "dNdy_stat": res_dndy_15_5["stat"],
    "dNdy_syst_down": res_dndy_15_5["syst_down"],
    "dNdy_syst_up": res_dndy_15_5["syst_up"],
}])

df_mb_integrated_15_5.to_csv(
    "output/final_integrated/cuau_mb_direct_gamma_dndy_15_5.csv",
    index=False
)

df_mb_integrated_15_5

pt: 1.5, val: 0.006848910716716341, stat: 0.003945980479416814, syst_down: 0.1302845117820101, syst_up: 0.1302845117820101
pt: 1.85, val: 0.0012765356715096186, stat: 0.0029177795450313878, syst_down: 0.06330499917373059, syst_up: 0.06330499917373059
pt: 2.25, val: 0.003714591608036816, stat: 0.0018850213224057854, syst_down: 0.034882393474139815, syst_up: 0.034882393474139815
pt: 2.75, val: 0.00022336199709437673, stat: 0.0007730746161532071, syst_down: 0.009609643719167248, syst_up: 0.009609643719167248
pt: 3.5, val: 0.0009555835648742974, stat: 0.00053832561708262, syst_down: 0.004168175594517669, syst_up: 0.004168175594517669
pt: 4.5, val: 0.0019175760541900375, stat: 0.0011114529919933446, syst_down: 0.0008739737607737756, syst_up: 0.004626885440640145

,system,label,pt_min,pt_max,dNch,dNch_err,dNdy,dNdy_stat,dNdy_syst_down,dNdy_syst_up
0,CuAu,This analysis MB,1.5,5.0,100.0,15.0,0.014937,0.011172,0.243124,0.246877